# FROM bde2020/spark-scala-template:2.4.0-hadoop2.7
FROM bde2020/spark-scala-template:latest

ENV SPARK_APPLICATION_MAIN_CLASS com.paytm.dataengineerchallenge.WebAnalyze

RUN cp -R /app/analyzer/target /app/target
